# Generated by Django 2.2.7 on 2019-11-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='point',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='mphone',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
